NewsWeb/Controllers/NewsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using NewsLogic;
using NewsLogic.Managers;
using NewsWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NewsWeb.Controllers
{
    public class NewsController : Controller
    {
        private TopicManager topics = new TopicManager();
        private NewsManager articles = new NewsManager();
        private IWebHostEnvironment webHost;

        public NewsController(IWebHostEnvironment host)
        {
            webHost = host;
        }

        public IActionResult Topics(int? id)
        {
            TopicsModel model = new TopicsModel();
            model.Topics = topics.GetAllTopics();
            if(id.HasValue)
            {
                // retrieve articles
                model.ActiveTopic = topics.GetTopic(id.Value);
                // retrieve active topic info
                model.Articles = articles.GetByTopic(id.Value);
            }

            return View(model);
        }

        // single article
        public IActionResult Article(int? id)
        {
            ArticleModel model = new ArticleModel();
            if(id.HasValue)
            {
                // one specific article is selected
                // select * from Articles
                model.Article = articles.GetById(id.Value);
                model.Topics = topics.GetAllTopics();
                // select * from Topics Where Id = Article.TopicId
                model.ArticleTopic = topics.GetTopic(model.Article.TopicId);

                model.Image = model.Article.Image;
            }

            return View(model);
        }

        public IActionResult Index()
        {
            if(!HttpContext.Session.GetIsAdmin())
            {
                return NotFound();
            }
            var data = articles.GetAll();

            return View(data);
        }

        public IActionResult Delete(int id)
        {
            if (!HttpContext.Session.GetIsAdmin())
            {
                return NotFound();
            }

            articles.Delete(id);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Create(int? id)
        {
            if (!HttpContext.Session.GetIsAdmin())
            {
                return NotFound();
            }

            var model = new CreateArticleModel();
            model.Author = HttpContext.Session.GetUsername();
            model.Topics = topics.GetAllTopics();

            if(id.HasValue)
            {
                var data = articles.GetById(id.Value);
                model.Author = data.Author;
                model.Id = data.Id;
                model.Text = data.Text;
                model.Title = data.Title;
                model.TopicId = data.TopicId;
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(CreateArticleModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    string image = UploadImage(model);
                    if (model.Id == 0)
                    {
                        articles.Create(model.TopicId, model.Title, model.Text, model.Author, image);
                    }
                    else
                    {
                        // id is defined -> update
                        articles.Update(model.Id, model.TopicId, model.Title, model.Text, model.Author, image);
                    }

                    return RedirectToAction(nameof(Index));
                }
                catch(LogicException ex)
                {
                    ModelState.AddModelError("validation", ex.Message);
                }
            }

            model.Topics = topics.GetAllTopics();
            return View(model);
        }

        private string UploadImage(CreateArticleModel model)
        {
            string fileName = null;

            if(model.Image != null)
            {
                string uploadsFolder = Path.Combine(webHost.WebRootPath, "ArticleImages");
                //cfd9906f-a702-4ae7-b92f-94823bc0da3f_sample.png
                fileName = Guid.NewGuid().ToString() + "_" + model.Image.FileName;
                string fullFilePath = Path.Combine(uploadsFolder, fileName);

                using(var fileStream = new FileStream(fullFilePath, FileMode.Create))
                {
                    model.Image.CopyTo(fileStream);
                }
            }

            return fileName;
        }
    }
}

NewsWeb/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NewsLogic;
using NewsLogic.Managers;
using NewsWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsWeb.Controllers
{
    public class UserController : Controller
    {
        private UserManager manager = new UserManager();

        [HttpGet]
        public IActionResult Register()
        {
            if(HttpContext.Session.IsSignedIn())
            {
                return NotFound();
            }

            return View();
        }

        [HttpPost]
        public IActionResult Register(RegisterUserModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    manager.Register(model.Username, model.Email, model.Password);

                    return RedirectToAction("Login");
                }
                catch(LogicException ex)
                {
                    ModelState.AddModelError("validation", ex.Message);
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (HttpContext.Session.IsSignedIn())
            {
                return NotFound();
            }

            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginUserModel model)
        {
            if(ModelState.IsValid)
            {
                var user = manager.GetUser(model.Username, model.Password);
                if(user == null)
                {
                    ModelState.AddModelError("validation", "Incorrect username/password!");
                }
                else
                {
                    HttpContext.Session.SetUsername(user.Username);
                    HttpContext.Session.SetIsAdmin(user.IsAdmin);

                    return RedirectToAction("Index", "Home");
                }
            }

            return View(model);
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

NewsWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewsWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
        <div class="container">
            <a class="navbar-brand" href="#">Best news</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item @(ViewContext.RouteData.Values["action"].ToString() == "Index" 
                        && ViewContext.RouteData.Values["controller"].ToString() == "Home" ? "active" : "")">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Latest news</a>
                    </li>
                    <li class="nav-item @(ViewContext.RouteData.Values["action"].ToString() == "Topics" ? "active" : "")">
                        <a class="nav-link" asp-controller="News" asp-action="Topics">Topics</a>
                    </li>
                    <li class="nav-item @(ViewContext.RouteData.Values["action"].ToString() == "About" ? "active" : "")">
                        <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    @if (Context.Session.GetIsAdmin())
                    {
                        <li class="nav-item @(ViewContext.RouteData.Values["action"].ToString() == "Index" && ViewContext.RouteData.Values["controller"].ToString() == "News" ? "active" : "")">
                            <a class="nav-link" asp-controller="News" asp-action="Index">Manage articles</a>
                        </li>
                        <li class="nav-item @(ViewContext.RouteData.Values["action"].ToString() == "Index" && ViewContext.RouteData.Values["controller"].ToString() == "Topic" ? "active" : "")">
                            <a class="nav-link" asp-controller="Topic" asp-action="Index">Manage topics</a>
                        </li>
                    }
                    @if (Context.Session.IsSignedIn())
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="#">Hello, @Context.Session.GetUsername()</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="User" asp-action="Logout">Sign out</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item @(ViewContext.RouteData.Values["action"].ToString() == "Register" ? "active" : "")">
                            <a class="nav-link" asp-controller="User" asp-action="Register">Sign up</a>
                        </li>
                        <li class="nav-item @(ViewContext.RouteData.Values["action"].ToString() == "Login" ? "active" : "")">
                            <a class="nav-link" asp-controller="User" asp-action="Login">Sign in</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NewsWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

NewsWeb/Views/Shared/_TopicMenu.cshtml
@model List<NewsLogic.DB.Topics> 